spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database_name  # Replace with your development database URL
    username: your_username  # Replace with your development database username
    password: your_password  # Replace with your development database password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: dev # Default profile is 'dev'

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db  # Test database URL
    username: test_user  # Test database username
    password: test_pass  # Test database password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # Recreate the schema for each test run
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



